### ISSUE TITLE
[1.0.0] MDBModal: Uncaught TypeError: p is not a function at eval (mdb-react-ui-kit.esm.js:95)

### ISSUE THREAD

**Issue by swayok** [mdbootstrap/mdb4-react-ui-kit#2]
It started failing after update from 1.0.0-beta7 to 1.0.0

```
mdb-react-ui-kit.esm.js:95 Uncaught TypeError: p is not a function
    at eval (mdb-react-ui-kit.esm.js:95)
eval @ mdb-react-ui-kit.esm.js:95
setTimeout (async)
eval @ mdb-react-ui-kit.esm.js:95
eval @ mdb-react-ui-kit.esm.js:95
invokePassiveEffectCreate @ react-dom.development.js:23482
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23569
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23442
performSyncWorkOnRoot @ react-dom.development.js:22264
eval @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
unbatchedUpdates @ react-dom.development.js:22433
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26015
render @ react-dom.development.js:26098
eval @ app.tsx:14
./resources/assets/user_account/app.tsx @ app.js:18
options.factory @ manifest.js:614
__webpack_require__ @ manifest.js:36
__webpack_exec__ @ app.js:553
(anonymous) @ app.js:554
__webpack_require__.O @ manifest.js:90
(anonymous) @ app.js:555
webpackJsonpCallback @ manifest.js:1268
(anonymous) @ app.js:9
```
JSX:
```
<MDBModal staticBackdrop show={debugModalContent !== null} tabIndex='-1'>
    <MDBModalDialog size="xl" centered>
        <MDBModalContent>
        </MDBModalContent>
    </MDBModalDialog>
</MDBModal>
```
It fails even like this
```
<MDBModal/>
```

**Comment by swayok** [comment]
Got more info:
```
Uncaught TypeError: getOpenState is not a function
    at eval (Modal.tsx:87)
eval @ Modal.tsx:87
setTimeout (async)
eval @ Modal.tsx:85
eval @ Modal.tsx:147
invokePassiveEffectCreate @ react-dom.development.js:23482
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
flushPassiveEffectsImpl @ react-dom.development.js:23569
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushPassiveEffects @ react-dom.development.js:23442
performSyncWorkOnRoot @ react-dom.development.js:22264
eval @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
unbatchedUpdates @ react-dom.development.js:22433
legacyRenderSubtreeIntoContainer @ react-dom.development.js:26015
render @ react-dom.development.js:26098
eval @ app.tsx:14
./resources/assets/user_account/app.tsx @ app.js:18
options.factory @ manifest.js:614
__webpack_require__ @ manifest.js:36
__webpack_exec__ @ app.js:564
(anonymous) @ app.js:565
__webpack_require__.O @ manifest.js:90
(anonymous) @ app.js:566
webpackJsonpCallback @ manifest.js:1268
(anonymous) @ app.js:9
```

**Comment by swayok** [comment]
I don't see this prop as required in prop types or any explanation about its purpose in docs. 
```
declare const MDBModal: React$1.FunctionComponent<{
        animationDirection?: string;
        backdrop?: boolean;
        className?: string;
        closeOnEsc?: boolean;
        tabIndex?: string;
        show?: boolean;
        staticBackdrop?: boolean;
        tag?: React$1.ComponentProps<any>;
        modalRef?: React$1.RefObject<HTMLElement>;
        [rest: string]: any;
    }>;
```

**Comment by Wojstan** [comment]
Thanks for Your report, we will fix this in the next release. For now, update the MDBModal component to look like this: 

<MDBModal staticBackdrop show={debugModalContent !== null} getOpenState={(e: any) => e} tabIndex='-1'>
    <MDBModalDialog size="xl" centered>
        <MDBModalContent>
        </MDBModalContent>
    </MDBModalDialog>
</MDBModal>

The problem is caused by the getOpenState property, which should be required except for the example with staticBackdrop.

**Comment by swayok** [comment]
Hi. Thanks for reply. I've already done that to fix error for the time being. 
While reviewing the code of `Modal.tsx` I came to realization that `getOpenState(true)`  is redundant because modal visibility is handled by `show` property and I can't think of any situation when modal can show itself avoiding `show` property.  In result only 
`getOpenState(false)` is meaningful. So why not rename `getOpenState` to more understandable `onClose` or `onBackdropClose` and call it only when modal closes by any means except `show` property?

**Comment by Wojstan** [comment]
Thanks for Your suggestion. We will think about changing the property name in the next release.
